## Import TensorFlow

To get started, import the `tensorflow` module. As of TensorFlow 2, eager execution is turned on by default. This enables a more interactive frontend to TensorFlow, the details of which we will discuss much later.

In [0]:
import tensorflow as tf

##Version Check

In [0]:
#rc- Release Candidate
print(tf.__version__)

2.2.0-rc3


## Tensors in 2.0

A Tensor is a multi-dimensional array. Similar to NumPy `ndarray` objects, `tf.Tensor` objects have a data type and a shape. Additionally, `tf.Tensor`s can reside in accelerator memory (like a GPU). TensorFlow offers a rich library of operations ([tf.add](https://www.tensorflow.org/api_docs/python/tf/add), [tf.matmul](https://www.tensorflow.org/api_docs/python/tf/matmul), [tf.linalg.inv](https://www.tensorflow.org/api_docs/python/tf/linalg/inv) etc.) that consume and produce `tf.Tensor`s. These operations automatically convert native Python types, for example:


In [0]:
# Hello Wrold 
msg = tf.constant('TensorFlow 2.0 Hello World')
tf.print(msg)

TensorFlow 2.0 Hello World


In [0]:
#Adding wo numbers
print(tf.add(1, 2))

tf.Tensor(3, shape=(), dtype=int32)


In [0]:
#Vector Sum
print(tf.add([1.0, 2.0], [3, 4]))

tf.Tensor([4. 6.], shape=(2,), dtype=float32)


In [0]:
#Sum of squares
print(tf.square(5))

tf.Tensor(25, shape=(), dtype=int32)


In [0]:
#Computing the sum of elements across dimensions of a tensor.
print(tf.reduce_sum([1, 2, 3]))

tf.Tensor(6, shape=(), dtype=int32)


In [0]:
#Seprate Sum
a = tf.constant([1, 2])
b = tf.constant([3, 4])
print(a + b)
print(a - b)
print(a * b)
print(a / b)

tf.Tensor([4 6], shape=(2,), dtype=int32)
tf.Tensor([-2 -2], shape=(2,), dtype=int32)
tf.Tensor([3 8], shape=(2,), dtype=int32)
tf.Tensor([0.33333333 0.5       ], shape=(2,), dtype=float64)


In [0]:
# Operator overloading is also supported
print(tf.square(2) + tf.square(3))

tf.Tensor(13, shape=(), dtype=int32)


Each `tf.Tensor` has a shape and a datatype:

In [0]:
#Matrix Multiplication
x = tf.matmul([[1]], [[2, 3]])
print(x)

tf.Tensor([[2 3]], shape=(1, 2), dtype=int32)


In [0]:
#Shape of matrix
print(x.shape)

(1, 2)


In [0]:
#Checking datatype of matrix
print(x.dtype)

<dtype: 'int32'>


The most obvious differences between NumPy arrays and `tf.Tensor`s are:

1. Tensors can be backed by accelerator memory (like GPU, TPU).
2. Tensors are immutable.